/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-10-09 06:34:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class foot_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<div class=\"foot\" align=\"center\">\n");
      out.write("\t<div class=\"content\">\n");
      out.write("\t\t<div class=\"oneThird\" align=\"left\">\n");
      out.write("\t\t\t<span class=\"caption\">下载QQ音乐客户端</span>\n");
      out.write("\t\t\t<ul class=\"clientIconUl\">\n");
      out.write("\t\t\t\t<li class=\"pc facility\"></li>\n");
      out.write("\t\t\t\t<li class=\"mac facility\"></li>\n");
      out.write("\t\t\t\t<li class=\"android facility\"></li>\n");
      out.write("\t\t\t\t<li class=\"iphone facility\"></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<ul class=\"clientTextUl\">\n");
      out.write("\t\t\t\t<li class=\"pcText facility\"><a>PC版</a></li>\n");
      out.write("\t\t\t\t<li class=\"macText facility\"><a>Mac版</a></li>\n");
      out.write("\t\t\t\t<li class=\"androidText facility\"><a>Android版</a></li>\n");
      out.write("\t\t\t\t<li class=\"iphoneText facility\"><a>iPhone版</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"twoThird\" align=\"left\">\n");
      out.write("\t\t\t<span class=\"caption\">特色产品</span>\n");
      out.write("\t\t\t<ul class=\"specialUl\">\n");
      out.write("\t\t\t\t<li class=\"kSound product\">\n");
      out.write("\t\t\t\t\t<i></i>\n");
      out.write("\t\t\t\t\t<span><a>全民K歌</a></span>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"superSound product\">\n");
      out.write("\t\t\t\t\t<i></i>\n");
      out.write("\t\t\t\t\t<span><a>Super Sound</a></span>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"qPlay product\">\n");
      out.write("\t\t\t\t\t<i></i>\n");
      out.write("\t\t\t\t\t<span><a>QPlay</a></span>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<div class=\"original\"><span><a>QQ音乐原创音乐平台</a></span></div>\n");
      out.write("\t\t\t<div  class=\"uploadVideo\"><span><a>上传视频</a></span></div>\n");
      out.write("\t\t\t<div  class=\"carConnect\"><span><a>车载互联</a></span></div>\n");
      out.write("\t\t\t<div  class=\"qqShow\"><span><a>QQ演出</a></span></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"threeThird\"  align=\"left\">\n");
      out.write("\t\t\t<span class=\"caption\">合作链接</span>\n");
      out.write("\t\t\t<table  class=\"linksTable\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"col1\"><a>CJ E&M</a></td>\n");
      out.write("\t\t\t\t\t<td class=\"col2\"><a>腾讯视频</a></td>\n");
      out.write("\t\t\t\t\t<td><a>手机QQ空间</a></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"col1\"><a>最新版QQ</a></td>\n");
      out.write("\t\t\t\t\t<td class=\"col2\"><a>腾讯社交广告</a></td>\n");
      out.write("\t\t\t\t\t<td><a>电脑管家</a></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"col1\"><a>QQ浏览器</a></td>\n");
      out.write("\t\t\t\t\t<td class=\"col2\"><a>画报</a></td>\n");
      out.write("\t\t\t\t\t<td><a>黄钻活动</a></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"col1\"><a>星钻</a></td>\n");
      out.write("\t\t\t\t\t<td class=\"col2\"><a>腾讯微云</a></td>\n");
      out.write("\t\t\t\t\t<td><a>更多</a></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"tail\" align=\"center\">\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<a>关于腾讯</a>|<a>About Tencent</a>|<a>服务条款</a>|<a>用户服务协议</a>|<a>隐私政策</a>|<a>广告服务</a>|<a>腾讯招聘</a>|<a>客服中心</a>|<a>网站导航</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"copyright\">\n");
      out.write("\t\t\t\tCopyright © 1998 - 2017 Tencent. <a>All Rights Reserved.</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"copyright\">\n");
      out.write("\t\t\t\t<a>腾讯公司</a><a>版权所有</a><a>腾讯网络文化经营许可证</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
