/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-10-09 07:10:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class album_005fdiscover_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fdebug_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fdebug_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fdebug_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>");
      if (_jspx_meth_s_005ftext_005f0(_jspx_page_context))
        return;
      out.write(" - 专辑库</title>\r\n");
      out.write("        <!-- 导库，开始 -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.2.0.min.js\"></script>\r\n");
      out.write("        <sx:head />\r\n");
      out.write("        <!-- 导库，结束 -->\r\n");
      out.write("        <!-- 模板js和css，开始 -->\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/template.css\" >\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/template.js\"></script>\r\n");
      out.write("        <!-- 模板js和css，结束 -->\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/img/logoIcon.png\" />\r\n");
      out.write("        <!-- 本页js和css，开始 -->\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/album_discover.css\" >\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/album_discover_content.css\" >\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/album_discover.js\"></script>\r\n");
      out.write("        <!-- 本页js和css，结束 -->\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    <!-- 用于快速回到开头 -->\r\n");
      out.write("    <a name=\"mao1\"></a>\r\n");
      out.write("        <!-- 模板头，开始 -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/head.jsp", out, false);
      out.write("\r\n");
      out.write("        <!-- 模板头，结束 -->\r\n");
      out.write("        <!-- 主体，开始 -->\r\n");
      out.write("         <div class=\"container\" align=\"center\">\r\n");
      out.write("         \t<div class=\"albumDisvcoverContent\">\r\n");
      out.write("         \t<input type='hidden' value=\"");
      if (_jspx_meth_s_005ftext_005f1(_jspx_page_context))
        return;
      out.write("\" id=\"allText\">\r\n");
      out.write("         \t\t<div class=\"languageBox\">\r\n");
      out.write("         \t\t\t<ul class=\"defaultUl languageUl\" optionClass=\"language\">\r\n");
      out.write("\t         \t\t\t<li class=\"optionClass\">");
      if (_jspx_meth_s_005ftext_005f2(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"all\">");
      if (_jspx_meth_s_005ftext_005f3(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"National\">");
      if (_jspx_meth_s_005ftext_005f4(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"Cantonese\">");
      if (_jspx_meth_s_005ftext_005f5(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"English\">");
      if (_jspx_meth_s_005ftext_005f6(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"Korea\">");
      if (_jspx_meth_s_005ftext_005f7(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"Japan\">");
      if (_jspx_meth_s_005ftext_005f8(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"French\">");
      if (_jspx_meth_s_005ftext_005f9(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"Spanish\">");
      if (_jspx_meth_s_005ftext_005f10(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t</ul>\r\n");
      out.write("         \t\t</div>\r\n");
      out.write("         \t\t<div class=\"genresBox\">\r\n");
      out.write("         \t\t\t<ul class=\"defaultUl genresUl\" optionClass=\"genres\">\r\n");
      out.write("\t         \t\t\t<li class=\"optionClass\">");
      if (_jspx_meth_s_005ftext_005f11(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"all\">");
      if (_jspx_meth_s_005ftext_005f12(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"fashion\">");
      if (_jspx_meth_s_005ftext_005f13(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"classical\">");
      if (_jspx_meth_s_005ftext_005f14(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"jazz\">");
      if (_jspx_meth_s_005ftext_005f15(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"rock\">");
      if (_jspx_meth_s_005ftext_005f16(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"electron\">");
      if (_jspx_meth_s_005ftext_005f17(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"latin\">");
      if (_jspx_meth_s_005ftext_005f18(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"light_music\">");
      if (_jspx_meth_s_005ftext_005f19(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"\">");
      if (_jspx_meth_s_005ftext_005f20(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"world_music\">");
      if (_jspx_meth_s_005ftext_005f21(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"original_sound\">");
      if (_jspx_meth_s_005ftext_005f22(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"country\">");
      if (_jspx_meth_s_005ftext_005f23(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"dance\">");
      if (_jspx_meth_s_005ftext_005f24(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"R&B\">");
      if (_jspx_meth_s_005ftext_005f25(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"ballad\">");
      if (_jspx_meth_s_005ftext_005f26(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"metal\">");
      if (_jspx_meth_s_005ftext_005f27(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t</ul>\r\n");
      out.write("         \t\t</div>\r\n");
      out.write("         \t\t<div class=\"priceBox\">\r\n");
      out.write("         \t\t\t<ul class=\"defaultUl priceUl\" optionClass=\"price\">\r\n");
      out.write("\t         \t\t\t<li class=\"optionClass\">");
      if (_jspx_meth_s_005ftext_005f28(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"all\">");
      if (_jspx_meth_s_005ftext_005f29(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"true\">");
      if (_jspx_meth_s_005ftext_005f30(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"false\">");
      if (_jspx_meth_s_005ftext_005f31(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t</ul>\r\n");
      out.write("         \t\t</div>\r\n");
      out.write("         \t\t<div class=\"filtrateBox\">\r\n");
      out.write("         \t\t\t<ul class=\"foldingUl filtrateUl\">\r\n");
      out.write("\t         \t\t\t<li class=\"foldingItemClass\" >");
      if (_jspx_meth_s_005ftext_005f32(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t         \t\t\t<li class=\"foldingItem\" selectedItem=\"false\" optionClass=\"category\"><span>");
      if (_jspx_meth_s_005ftext_005f33(_jspx_page_context))
        return;
      out.write("</span><i class=\"downIcon\"></i></li>\r\n");
      out.write("\t         \t\t\t<li class=\"foldingItem\" selectedItem=\"false\" optionClass=\"years\" ><span>");
      if (_jspx_meth_s_005ftext_005f34(_jspx_page_context))
        return;
      out.write("</span><i class=\"downIcon\"></i></li>\r\n");
      out.write("\t         \t\t\t<li class=\"foldingItem\" selectedItem=\"false\" optionClass=\"albumCompany\" ><span>");
      if (_jspx_meth_s_005ftext_005f35(_jspx_page_context))
        return;
      out.write("</span><i class=\"downIcon\"></i></li>\r\n");
      out.write("\t         \t\t</ul>\r\n");
      out.write("\t         \t\t<div class=\"unfoldBox\" optionClass=\"category\">\r\n");
      out.write("\t         \t\t\t<ul class=\"defaultUl categoryUl\" optionClass=\"category\">\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"all\">");
      if (_jspx_meth_s_005ftext_005f36(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"album\">");
      if (_jspx_meth_s_005ftext_005f37(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"EP\">");
      if (_jspx_meth_s_005ftext_005f38(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"Single\">");
      if (_jspx_meth_s_005ftext_005f39(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"concert\">");
      if (_jspx_meth_s_005ftext_005f40(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"cartoon\">");
      if (_jspx_meth_s_005ftext_005f41(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"game\">");
      if (_jspx_meth_s_005ftext_005f42(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t</ul>\r\n");
      out.write("\t         \t\t</div>\r\n");
      out.write("\t         \t\t<div class=\"unfoldBox\" optionClass=\"years\">\r\n");
      out.write("\t         \t\t\t<ul class=\"defaultUl yearsUl\" optionClass=\"years\">\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"all\">");
      if (_jspx_meth_s_005ftext_005f43(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"2017.01.01-2017.12.31\">2017</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"2016.01.01-2016.12.31\">2016</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"2015.01.01-2015.12.31\">2015</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"2014.01.01-2014.12.31\">2014</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"2013.01.01-2013.12.31\">2013</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"2012.01.01-2012.12.31\">2012</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"2010.01.01-2019.12.31\">");
      if (_jspx_meth_s_005ftext_005f44(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"2000.01.01-2009.12.31\">");
      if (_jspx_meth_s_005ftext_005f45(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"1990.01.01-1999.12.31\">");
      if (_jspx_meth_s_005ftext_005f46(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"1980.01.01-1989.12.31\">");
      if (_jspx_meth_s_005ftext_005f47(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"1970.01.01-1979.12.31\">");
      if (_jspx_meth_s_005ftext_005f48(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"1960.01.01-1999.12.31\">");
      if (_jspx_meth_s_005ftext_005f49(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t</ul>\r\n");
      out.write("\t         \t\t</div>\r\n");
      out.write("\t         \t\t<div class=\"unfoldBox\" optionClass=\"albumCompany\">\r\n");
      out.write("\t         \t\t\t<ul class=\"defaultUl albumCompanyUl\" optionClass=\"albumCompany\">\r\n");
      out.write("\t\t         \t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"all\">");
      if (_jspx_meth_s_005ftext_005f50(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t         \t\t\t");
      if (_jspx_meth_s_005fiterator_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t         \t\t</ul>\r\n");
      out.write("\t         \t\t</div>\r\n");
      out.write("\t         \t\t\r\n");
      out.write("         \t\t</div>\r\n");
      out.write("         \t\t<div class=\"haveSelectedBox\" align=\"left\">\r\n");
      out.write("         \t\t\t<div class=\"allALbumText\">");
      if (_jspx_meth_s_005ftext_005f51(_jspx_page_context))
        return;
      if (_jspx_meth_s_005ftext_005f52(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("         \t\t\t<div category=\"language\" class=\"haveSelectedItem\"><span></span><i></i></div>\r\n");
      out.write("         \t\t\t<div category=\"genres\" class=\"haveSelectedItem\"><span></span><i></i></div>\r\n");
      out.write("         \t\t\t<div category=\"price\" class=\"haveSelectedItem\"><span></span><i></i></div>\r\n");
      out.write("         \t\t\t<div category=\"category\" class=\"haveSelectedItem\"><span></span><i></i></div>\r\n");
      out.write("         \t\t\t<div category=\"years\" class=\"haveSelectedItem\"><span></span><i></i></div>\r\n");
      out.write("         \t\t\t<div category=\"albumCompany\" class=\"haveSelectedItem\"><span></span><i></i></div>\r\n");
      out.write("         \t\t\t<div class=\"orderBy hottestBtn\" align=\"center\">");
      if (_jspx_meth_s_005ftext_005f53(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("         \t\t\t<div class=\"orderBy newestBtn\" align=\"center\">");
      if (_jspx_meth_s_005ftext_005f54(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("         \t\t</div>\r\n");
      out.write("         \t\t<div class=\"detailContent\" align=\"center\">\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("         \t</div>\r\n");
      out.write("         </div>\r\n");
      out.write("        <!-- 固定Div开始 -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/fixed_div.jsp", out, false);
      out.write("\r\n");
      out.write("        <!-- 固定Div结束 -->\r\n");
      out.write("        <!-- 主体，结束 -->\r\n");
      out.write("        <!-- 模板尾，开始 -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/foot.jsp", out, false);
      out.write("\r\n");
      out.write("        <!-- 模板尾，结束 -->\r\n");
      out.write("        ");
      if (_jspx_meth_s_005fdebug_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ftext_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f0 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f0.setParent(null);
      // /content/album_discover.jsp(8,15) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f0.setName("QQMusic");
      int _jspx_eval_s_005ftext_005f0 = _jspx_th_s_005ftext_005f0.doStartTag();
      if (_jspx_th_s_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f1 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f1.setParent(null);
      // /content/album_discover.jsp(33,38) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f1.setName("all");
      int _jspx_eval_s_005ftext_005f1 = _jspx_th_s_005ftext_005f1.doStartTag();
      if (_jspx_th_s_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f2 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f2.setParent(null);
      // /content/album_discover.jsp(36,37) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f2.setName("language");
      int _jspx_eval_s_005ftext_005f2 = _jspx_th_s_005ftext_005f2.doStartTag();
      if (_jspx_th_s_005ftext_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f3 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f3.setParent(null);
      // /content/album_discover.jsp(37,67) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f3.setName("all");
      int _jspx_eval_s_005ftext_005f3 = _jspx_th_s_005ftext_005f3.doStartTag();
      if (_jspx_th_s_005ftext_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f4 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f4.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f4.setParent(null);
      // /content/album_discover.jsp(38,72) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f4.setName("National");
      int _jspx_eval_s_005ftext_005f4 = _jspx_th_s_005ftext_005f4.doStartTag();
      if (_jspx_th_s_005ftext_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f5 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f5.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f5.setParent(null);
      // /content/album_discover.jsp(39,73) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f5.setName("Cantonese");
      int _jspx_eval_s_005ftext_005f5 = _jspx_th_s_005ftext_005f5.doStartTag();
      if (_jspx_th_s_005ftext_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f6 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f6.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f6.setParent(null);
      // /content/album_discover.jsp(40,71) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f6.setName("English");
      int _jspx_eval_s_005ftext_005f6 = _jspx_th_s_005ftext_005f6.doStartTag();
      if (_jspx_th_s_005ftext_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f7 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f7.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f7.setParent(null);
      // /content/album_discover.jsp(41,69) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f7.setName("Korea");
      int _jspx_eval_s_005ftext_005f7 = _jspx_th_s_005ftext_005f7.doStartTag();
      if (_jspx_th_s_005ftext_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f8 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f8.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f8.setParent(null);
      // /content/album_discover.jsp(42,69) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f8.setName("Japan");
      int _jspx_eval_s_005ftext_005f8 = _jspx_th_s_005ftext_005f8.doStartTag();
      if (_jspx_th_s_005ftext_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f8);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f9 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f9.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f9.setParent(null);
      // /content/album_discover.jsp(43,70) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f9.setName("French");
      int _jspx_eval_s_005ftext_005f9 = _jspx_th_s_005ftext_005f9.doStartTag();
      if (_jspx_th_s_005ftext_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f9);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f10 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f10.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f10.setParent(null);
      // /content/album_discover.jsp(44,71) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f10.setName("Spanish");
      int _jspx_eval_s_005ftext_005f10 = _jspx_th_s_005ftext_005f10.doStartTag();
      if (_jspx_th_s_005ftext_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f10);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f11 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f11.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f11.setParent(null);
      // /content/album_discover.jsp(49,37) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f11.setName("genres");
      int _jspx_eval_s_005ftext_005f11 = _jspx_th_s_005ftext_005f11.doStartTag();
      if (_jspx_th_s_005ftext_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f11);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f12 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f12.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f12.setParent(null);
      // /content/album_discover.jsp(50,67) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f12.setName("all");
      int _jspx_eval_s_005ftext_005f12 = _jspx_th_s_005ftext_005f12.doStartTag();
      if (_jspx_th_s_005ftext_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f12);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f13 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f13.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f13.setParent(null);
      // /content/album_discover.jsp(51,71) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f13.setName("fashion");
      int _jspx_eval_s_005ftext_005f13 = _jspx_th_s_005ftext_005f13.doStartTag();
      if (_jspx_th_s_005ftext_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f13);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f14 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f14.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f14.setParent(null);
      // /content/album_discover.jsp(52,73) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f14.setName("classical");
      int _jspx_eval_s_005ftext_005f14 = _jspx_th_s_005ftext_005f14.doStartTag();
      if (_jspx_th_s_005ftext_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f14);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f15 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f15.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f15.setParent(null);
      // /content/album_discover.jsp(53,68) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f15.setName("jazz");
      int _jspx_eval_s_005ftext_005f15 = _jspx_th_s_005ftext_005f15.doStartTag();
      if (_jspx_th_s_005ftext_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f15);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f16 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f16.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f16.setParent(null);
      // /content/album_discover.jsp(54,68) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f16.setName("rock");
      int _jspx_eval_s_005ftext_005f16 = _jspx_th_s_005ftext_005f16.doStartTag();
      if (_jspx_th_s_005ftext_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f16);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f17 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f17.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f17.setParent(null);
      // /content/album_discover.jsp(55,72) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f17.setName("electron");
      int _jspx_eval_s_005ftext_005f17 = _jspx_th_s_005ftext_005f17.doStartTag();
      if (_jspx_th_s_005ftext_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f17);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f18(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f18 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f18.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f18.setParent(null);
      // /content/album_discover.jsp(56,69) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f18.setName("latin");
      int _jspx_eval_s_005ftext_005f18 = _jspx_th_s_005ftext_005f18.doStartTag();
      if (_jspx_th_s_005ftext_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f18);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f19(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f19 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f19.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f19.setParent(null);
      // /content/album_discover.jsp(57,75) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f19.setName("light_music");
      int _jspx_eval_s_005ftext_005f19 = _jspx_th_s_005ftext_005f19.doStartTag();
      if (_jspx_th_s_005ftext_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f19);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f20(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f20 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f20.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f20.setParent(null);
      // /content/album_discover.jsp(58,64) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f20.setName("world_music");
      int _jspx_eval_s_005ftext_005f20 = _jspx_th_s_005ftext_005f20.doStartTag();
      if (_jspx_th_s_005ftext_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f20);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f21(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f21 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f21.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f21.setParent(null);
      // /content/album_discover.jsp(59,75) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f21.setName("Hip_hop");
      int _jspx_eval_s_005ftext_005f21 = _jspx_th_s_005ftext_005f21.doStartTag();
      if (_jspx_th_s_005ftext_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f21);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f22(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f22 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f22.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f22.setParent(null);
      // /content/album_discover.jsp(60,78) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f22.setName("original_sound");
      int _jspx_eval_s_005ftext_005f22 = _jspx_th_s_005ftext_005f22.doStartTag();
      if (_jspx_th_s_005ftext_005f22.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f22);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f23(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f23 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f23.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f23.setParent(null);
      // /content/album_discover.jsp(61,71) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f23.setName("country");
      int _jspx_eval_s_005ftext_005f23 = _jspx_th_s_005ftext_005f23.doStartTag();
      if (_jspx_th_s_005ftext_005f23.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f23);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f24(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f24 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f24.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f24.setParent(null);
      // /content/album_discover.jsp(62,69) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f24.setName("dance");
      int _jspx_eval_s_005ftext_005f24 = _jspx_th_s_005ftext_005f24.doStartTag();
      if (_jspx_th_s_005ftext_005f24.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f24);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f25(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f25 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f25.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f25.setParent(null);
      // /content/album_discover.jsp(63,67) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f25.setName("R&B");
      int _jspx_eval_s_005ftext_005f25 = _jspx_th_s_005ftext_005f25.doStartTag();
      if (_jspx_th_s_005ftext_005f25.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f25);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f26(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f26 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f26.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f26.setParent(null);
      // /content/album_discover.jsp(64,70) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f26.setName("ballad");
      int _jspx_eval_s_005ftext_005f26 = _jspx_th_s_005ftext_005f26.doStartTag();
      if (_jspx_th_s_005ftext_005f26.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f26);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f27(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f27 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f27.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f27.setParent(null);
      // /content/album_discover.jsp(65,69) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f27.setName("metal");
      int _jspx_eval_s_005ftext_005f27 = _jspx_th_s_005ftext_005f27.doStartTag();
      if (_jspx_th_s_005ftext_005f27.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f27);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f28(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f28 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f28.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f28.setParent(null);
      // /content/album_discover.jsp(70,37) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f28.setName("price");
      int _jspx_eval_s_005ftext_005f28 = _jspx_th_s_005ftext_005f28.doStartTag();
      if (_jspx_th_s_005ftext_005f28.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f28);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f29(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f29 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f29.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f29.setParent(null);
      // /content/album_discover.jsp(71,67) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f29.setName("all");
      int _jspx_eval_s_005ftext_005f29 = _jspx_th_s_005ftext_005f29.doStartTag();
      if (_jspx_th_s_005ftext_005f29.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f29);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f30(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f30 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f30.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f30.setParent(null);
      // /content/album_discover.jsp(72,68) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f30.setName("free");
      int _jspx_eval_s_005ftext_005f30 = _jspx_th_s_005ftext_005f30.doStartTag();
      if (_jspx_th_s_005ftext_005f30.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f30);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f31(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f31 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f31.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f31.setParent(null);
      // /content/album_discover.jsp(73,69) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f31.setName("pay");
      int _jspx_eval_s_005ftext_005f31 = _jspx_th_s_005ftext_005f31.doStartTag();
      if (_jspx_th_s_005ftext_005f31.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f31);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f32(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f32 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f32.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f32.setParent(null);
      // /content/album_discover.jsp(78,43) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f32.setName("filtrate");
      int _jspx_eval_s_005ftext_005f32 = _jspx_th_s_005ftext_005f32.doStartTag();
      if (_jspx_th_s_005ftext_005f32.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f32);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f33(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f33 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f33.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f33.setParent(null);
      // /content/album_discover.jsp(79,87) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f33.setName("category");
      int _jspx_eval_s_005ftext_005f33 = _jspx_th_s_005ftext_005f33.doStartTag();
      if (_jspx_th_s_005ftext_005f33.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f33);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f34(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f34 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f34.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f34.setParent(null);
      // /content/album_discover.jsp(80,85) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f34.setName("years");
      int _jspx_eval_s_005ftext_005f34 = _jspx_th_s_005ftext_005f34.doStartTag();
      if (_jspx_th_s_005ftext_005f34.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f34);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f35(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f35 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f35.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f35.setParent(null);
      // /content/album_discover.jsp(81,92) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f35.setName("albumCompany");
      int _jspx_eval_s_005ftext_005f35 = _jspx_th_s_005ftext_005f35.doStartTag();
      if (_jspx_th_s_005ftext_005f35.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f35);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f36(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f36 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f36.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f36.setParent(null);
      // /content/album_discover.jsp(85,68) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f36.setName("all");
      int _jspx_eval_s_005ftext_005f36 = _jspx_th_s_005ftext_005f36.doStartTag();
      if (_jspx_th_s_005ftext_005f36.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f36);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f37(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f37 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f37.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f37.setParent(null);
      // /content/album_discover.jsp(86,70) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f37.setName("album");
      int _jspx_eval_s_005ftext_005f37 = _jspx_th_s_005ftext_005f37.doStartTag();
      if (_jspx_th_s_005ftext_005f37.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f37);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f38(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f38 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f38.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f38.setParent(null);
      // /content/album_discover.jsp(87,67) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f38.setName("EP");
      int _jspx_eval_s_005ftext_005f38 = _jspx_th_s_005ftext_005f38.doStartTag();
      if (_jspx_th_s_005ftext_005f38.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f38);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f39(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f39 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f39.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f39.setParent(null);
      // /content/album_discover.jsp(88,71) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f39.setName("Single");
      int _jspx_eval_s_005ftext_005f39 = _jspx_th_s_005ftext_005f39.doStartTag();
      if (_jspx_th_s_005ftext_005f39.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f39);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f40(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f40 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f40.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f40.setParent(null);
      // /content/album_discover.jsp(89,72) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f40.setName("concert");
      int _jspx_eval_s_005ftext_005f40 = _jspx_th_s_005ftext_005f40.doStartTag();
      if (_jspx_th_s_005ftext_005f40.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f40);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f41(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f41 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f41.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f41.setParent(null);
      // /content/album_discover.jsp(90,72) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f41.setName("cartoon");
      int _jspx_eval_s_005ftext_005f41 = _jspx_th_s_005ftext_005f41.doStartTag();
      if (_jspx_th_s_005ftext_005f41.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f41);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f42(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f42 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f42.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f42.setParent(null);
      // /content/album_discover.jsp(91,69) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f42.setName("game");
      int _jspx_eval_s_005ftext_005f42 = _jspx_th_s_005ftext_005f42.doStartTag();
      if (_jspx_th_s_005ftext_005f42.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f42);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f43(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f43 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f43.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f43.setParent(null);
      // /content/album_discover.jsp(96,68) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f43.setName("all");
      int _jspx_eval_s_005ftext_005f43 = _jspx_th_s_005ftext_005f43.doStartTag();
      if (_jspx_th_s_005ftext_005f43.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f43);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f44(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f44 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f44.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f44.setParent(null);
      // /content/album_discover.jsp(103,86) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f44.setName("yearsOf10");
      int _jspx_eval_s_005ftext_005f44 = _jspx_th_s_005ftext_005f44.doStartTag();
      if (_jspx_th_s_005ftext_005f44.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f44);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f45(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f45 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f45.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f45.setParent(null);
      // /content/album_discover.jsp(104,86) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f45.setName("yearsOf00");
      int _jspx_eval_s_005ftext_005f45 = _jspx_th_s_005ftext_005f45.doStartTag();
      if (_jspx_th_s_005ftext_005f45.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f45);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f46(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f46 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f46.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f46.setParent(null);
      // /content/album_discover.jsp(105,86) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f46.setName("yearsOf90");
      int _jspx_eval_s_005ftext_005f46 = _jspx_th_s_005ftext_005f46.doStartTag();
      if (_jspx_th_s_005ftext_005f46.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f46);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f47(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f47 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f47.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f47.setParent(null);
      // /content/album_discover.jsp(106,86) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f47.setName("yearsOf80");
      int _jspx_eval_s_005ftext_005f47 = _jspx_th_s_005ftext_005f47.doStartTag();
      if (_jspx_th_s_005ftext_005f47.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f47);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f48(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f48 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f48.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f48.setParent(null);
      // /content/album_discover.jsp(107,86) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f48.setName("yearsOf70");
      int _jspx_eval_s_005ftext_005f48 = _jspx_th_s_005ftext_005f48.doStartTag();
      if (_jspx_th_s_005ftext_005f48.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f48);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f49(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f49 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f49.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f49.setParent(null);
      // /content/album_discover.jsp(108,86) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f49.setName("yearsOf60");
      int _jspx_eval_s_005ftext_005f49 = _jspx_th_s_005ftext_005f49.doStartTag();
      if (_jspx_th_s_005ftext_005f49.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f49);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f50(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f50 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f50.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f50.setParent(null);
      // /content/album_discover.jsp(113,68) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f50.setName("all");
      int _jspx_eval_s_005ftext_005f50 = _jspx_th_s_005ftext_005f50.doStartTag();
      if (_jspx_th_s_005ftext_005f50.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f50);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fiterator_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f0 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.get(org.apache.struts2.views.jsp.IteratorTag.class);
    try {
      _jspx_th_s_005fiterator_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fiterator_005f0.setParent(null);
      // /content/album_discover.jsp(114,14) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fiterator_005f0.setValue("top23Company");
      int _jspx_eval_s_005fiterator_005f0 = _jspx_th_s_005fiterator_005f0.doStartTag();
      if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_s_005fiterator_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_s_005fiterator_005f0.doInitBody();
        }
        do {
          out.write("\r\n");
          out.write("\t\t         \t\t\t\t<li class=\"optionItem\" selectedItem=\"false\" val=\"");
          if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
            return true;
          out.write('"');
          out.write('>');
          if (_jspx_meth_s_005fproperty_005f1(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t         \t\t\t");
          int evalDoAfterBody = _jspx_th_s_005fiterator_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fiterator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.reuse(_jspx_th_s_005fiterator_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    try {
      _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
      // /content/album_discover.jsp(115,64) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f0.setValue("companyId");
      int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
      if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    try {
      _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
      // /content/album_discover.jsp(115,97) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f1.setValue("comName");
      int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
      if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f51(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f51 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f51.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f51.setParent(null);
      // /content/album_discover.jsp(122,38) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f51.setName("all");
      int _jspx_eval_s_005ftext_005f51 = _jspx_th_s_005ftext_005f51.doStartTag();
      if (_jspx_th_s_005ftext_005f51.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f51);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f52(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f52 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f52.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f52.setParent(null);
      // /content/album_discover.jsp(122,58) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f52.setName("album");
      int _jspx_eval_s_005ftext_005f52 = _jspx_th_s_005ftext_005f52.doStartTag();
      if (_jspx_th_s_005ftext_005f52.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f52);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f53(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f53 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f53.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f53.setParent(null);
      // /content/album_discover.jsp(129,59) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f53.setName("hottest");
      int _jspx_eval_s_005ftext_005f53 = _jspx_th_s_005ftext_005f53.doStartTag();
      if (_jspx_th_s_005ftext_005f53.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f53);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftext_005f54(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:text
    org.apache.struts2.views.jsp.TextTag _jspx_th_s_005ftext_005f54 = (org.apache.struts2.views.jsp.TextTag) _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.get(org.apache.struts2.views.jsp.TextTag.class);
    try {
      _jspx_th_s_005ftext_005f54.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftext_005f54.setParent(null);
      // /content/album_discover.jsp(130,58) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftext_005f54.setName("newest");
      int _jspx_eval_s_005ftext_005f54 = _jspx_th_s_005ftext_005f54.doStartTag();
      if (_jspx_th_s_005ftext_005f54.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_s_005ftext_005f54);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fdebug_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:debug
    org.apache.struts2.views.jsp.ui.DebugTag _jspx_th_s_005fdebug_005f0 = (org.apache.struts2.views.jsp.ui.DebugTag) _005fjspx_005ftagPool_005fs_005fdebug_005fnobody.get(org.apache.struts2.views.jsp.ui.DebugTag.class);
    try {
      _jspx_th_s_005fdebug_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fdebug_005f0.setParent(null);
      int _jspx_eval_s_005fdebug_005f0 = _jspx_th_s_005fdebug_005f0.doStartTag();
      if (_jspx_th_s_005fdebug_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fs_005fdebug_005fnobody.reuse(_jspx_th_s_005fdebug_005f0);
    }
    return false;
  }
}
